### ISSUE TITLE
System.ObjectDisposedException on WebAuthenticatorActivity in onBackPressed

### ISSUE THREAD

**Issue by JakubHolovsky** [xamarin/Xamarin.Auth#153]
Package: com.psonar.android
Version Code: 19797
Version Name: 4.17.0
Android: 6.0
Android Build: MRA58K release-keys
Manufacturer: TCL
Model: 5045T
Thread: main-1
CrashReporter Key: 7E4686C5-10E5-9F5D-A510-8B884A8ACD84C63E8143
Start Date: Mon Mar 13 15:06:23 GMT+08:00 2017
Date: Mon Mar 13 15:25:08 GMT+08:00 2017
Format: Xamarin

Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Psonar.Apps.Droid.PayPerPlay.LoginActivity'.
	at md5a104545e4d19c4ffe9ec3d5074a3b979.WebAuthenticatorActivity.n_onBackPressed(Native Method)
	at md5a104545e4d19c4ffe9ec3d5074a3b979.WebAuthenticatorActivity.onBackPressed(WebAuthenticatorActivity.java:49)
	at android.app.Activity.onKeyUp(Activity.java:2511)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2669)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2764)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2366)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4637)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4593)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4271)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4328)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4304)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4474)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2330)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1934)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1925)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2307)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:328)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:5774)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by newky2k** [comment]
@JakubHolovsky Is this still and issue?  can you try it with the latest version and if so can you please provide more details on the code you are using plus a sample project so we can replicate it

Regards

**Comment by JakubHolovsky** [comment]
@newky2k sorry, I don't have an access to that project anymore. So feel free to close it if you like.
