### ISSUE TITLE
NullReferenceException in presenter.Login on Windows-desktop

### ISSUE THREAD

**Issue by TomQv** [xamarin/Xamarin.Auth#244]
I'm trying to use Xamarin.Auth 1.5.0.3 in a Windows.Forms app, but get NullReferenceException  in 

var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
presenter.Login(authenticator);

I followed [this tutorial](https://developer.xamarin.com/guides/xamarin-forms/cloud-services/authentication/oauth/) but I also need Windows.Forms and Xamarin.Mac. Most probably I need to change something because its desktop and not mobile, but was is the correct way to initialise the Login-UI on desktop?

Thanks
Tom

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=Xamarin.Auth
  StackTrace:
   at Xamarin.Auth.Presenters.OAuthLoginPresenter.Login(Authenticator authenticator)
   at Test.Win.Form1.btnLoginGoogle_Click(Object sender, EventArgs e) in C:\Users\Tom\QuoVadis\QvxCloud\Test.Win\Form1.cs:line 50
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Test.Win.Program.Main() in C:\Users\Tom\QuoVadis\QvxCloud\Test.Win\Program.cs:line 19

**Comment by moljac** [comment]
@TomQv 

> trying to use Xamarin.Auth 1.5.0.3 in a Windows.Forms

Windows.Forms? Not ready yet. Planned.

**Comment by Redth** [comment]
Sorry, windows.forms support is not currently on our roadmap.
