### ISSUE TITLE
OAuth2Authenticator crashes on Android using native UI

### ISSUE THREAD

**Issue by tipa** [xamarin/Xamarin.Auth#322]
### Version & Platform

- [ ] nuget version = 1.6.0.2
- [ ] component version = 27.0.2.1
- [ ] Xamarin.Android 9.0.0.20
- [ ] Targeting Android P

### Steps to reproduce

```
var authenticator = new OAuth2Authenticator(
  ClientId + ".apps.googleusercontent.com",
  "myClientSecret",
  "https://www.googleapis.com/auth/drive.file",
  new Uri("https://accounts.google.com/o/oauth2/v2/auth"),
  new Uri($"com.googleusercontent.apps.{ClientId}:/oauth2redirect"),
  new Uri("https://accounts.google.com/o/oauth2/token"),
  null, true);
activity.StartActivity(authenticator.GetUI(activity));
```

### Expected behaviour

The user can log into Google and grant the app permissions for Google Drive

### Actual behaviour

The app crashes:
```
System.Collections.Generic.KeyNotFoundException: The given key 'CANARY_PACKAGE' was not present in the dictionary.

Dictionary`2[TKey,TValue].get_Item (TKey key)
PackageManagerHelper.GetPackageNamesToUseImplementation (Android.Content.Context context, System.String url)
CustomTabsConfiguration.Initialize (Android.App.Activity a)
WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState)
Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
(wrapper dynamic-method) System.Object.17(intptr,intptr,intptr)
```

Happens only for a few users, on devices like:
Galaxy A5(2016) - Android 7.0
P10 - Android 7.0
Mi A2 - Android 8.1.0
MIX 2S - Android 8.0.0
Galaxy Note8 - Android 8.0.0

**Comment by newky2k** [comment]
@tipa  are you able to replicate this is the simulator with a similar config?  could you please send a sample project with all of the permissions etc configured to make it easier for us to replicate.

Regards

**Comment by tipa** [comment]
No I cannot reproduce the crash in a simulator (got the stack trace from AppCenter), but wouldn't it be possible to add a `PackagesSupportingCustomTabs.ContainsKey("CANARY_PACKAGE")` here?
https://github.com/xamarin/Xamarin.Auth/blob/d592c51a6f91aa073f0c1be8a768c464aa6e62a7/source/Core/Xamarin.Auth.XamarinAndroid/UINativeNonIntegratedBrowsers/CustomTabsUtilities/PackageManagerHelper.cs#L202

**Comment by moljac** [comment]
Seems like that device is missing Chrome/Chrome Cannary. This will be a resource intensive fix, due to the need to finish testing of ported Google library with extended Package tests.

triaging it as "Low Priority"

In order to speed up the bugfixing, add link to the repo with minimal sample (with removed sensitve data)

**Comment by qoob23** [comment]
I was facing same issue cause I disabled Chrome. So when I enabled it everything goes fine, except... I see Yandex Browser (which is my default) menu in custom tab. Why do I need Chrome then?
https://user-images.githubusercontent.com/30430081/66523347-69d70900-eaf8-11e9-97c7-a009e72be635.jpg

**Comment by mjromka** [comment]
Met this with the following stack trace:
```
Exception: System.Collections.Generic.KeyNotFoundException: The given key 'CANARY_PACKAGE' was not present in the dictionary.
 at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <6bf884a45a6a40c3bb65983b895bc705>:0 
 at Android.Support.CustomTabs.Chromium.SharedUtilities.PackageManagerHelper.GetPackageNamesToUseImplementation (Android.Content.Context context, System.String url) [0x001e3] in <3887a0d7d292416b83829cf88b593985>:0 
 at Xamarin.Auth.CustomTabsConfiguration.Initialize (Android.App.Activity a) [0x00010] in <3887a0d7d292416b83829cf88b593985>:0 
 at Xamarin.Auth.WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000ad] in <3887a0d7d292416b83829cf88b593985>:0 
 at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <491175723b6749d9a78536bb65876c3b>:0 
 at (wrapper dynamic-method) System.Object.8(intptr,intptr,intptr)
```
Android API 28
Is there any workaround I can provide to a customer?

**Comment by tipa** [comment]
Will there be any attempts made to fix this problem? The worst part is that I cannot try-catch the exception in my code, basically a crash that I cannot avoid when using Xamarin.Auth.

Please let me know if you need any additional information regarding this problem

**Comment by alwydl** [comment]
Same issue for me. App closes and the user thinks is our app that is of poor quality making. We only got this, because the user is a friend and reported. We don`t have any ideas of to how many this could have happened.
It is in a xiaomi mi note 3 with Android 9.

stack:
android.runtime.JavaProxyThrowable: System.Collections.Generic.KeyNotFoundException: The given key 'CANARY_PACKAGE' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <9594e5c1ea964e75a5b926e730e75010>:0 
  at Android.Support.CustomTabs.Chromium.SharedUtilities.PackageManagerHelper.GetPackageNamesToUseImplementation (Android.Content.Context context, System.String url) [0x001e3] in <98de59c6304c4348ab7c355151c2702f>:0 
  at Xamarin.Auth.CustomTabsConfiguration.Initialize (Android.App.Activity a) [0x00010] in <98de59c6304c4348ab7c355151c2702f>:0 
  at Xamarin.Auth.WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000ad] in <98de59c6304c4348ab7c355151c2702f>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <91c8036187f34cdabde47f7b2f3ab9c2>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.9(intptr,intptr,intptr)
	at md5538102cb7512c6dba0c04fe6c395414e.WebAuthenticatorNativeBrowserActivity.n_onCreate(Native Method)
	at md5538102cb7512c6dba0c04fe6c395414e.WebAuthenticatorNativeBrowserActivity.onCreate(WebAuthenticatorNativeBrowserActivity.java:34)
	at android.app.Activity.performCreate(Unknown Source:16)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:368)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:36)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:57)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:99)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:34)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:36)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:207)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

**Comment by akamud** [comment]
We are having this too, this is the stack trace from AppCenter:

```
Dictionary`2[TKey,TValue].get_Item (TKey key)
PackageManagerHelper.GetPackageNamesToUseImplementation (Android.Content.Context context, System.String url)
CustomTabsConfiguration.Initialize (Android.App.Activity a)
WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState)
Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.18(intptr,intptr,intptr)
```

**Comment by tipa** [comment]
I gave up waiting for a fix for this (and other) issues and switched to [AppAuth.Android](https://www.nuget.org/packages/Xamarin.OpenId.AppAuth.Android/), which works beautifully so far

**Comment by fernandovm** [comment]
I have the same problem:

Android: 10
Android Build: QP1A.190711.020
Manufacturer: samsung
Model: SM-A305GT

Xamarin Exception Stack:
System.Collections.Generic.KeyNotFoundException: The given key 'CANARY_PACKAGE' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) <0x77aca39a78 + 0x0007f> in <245c2548bdff47bb82a0817b9e9c956c>:0
  at Android.Support.CustomTabs.Chromium.SharedUtilities.PackageManagerHelper.GetPackageNamesToUseImplementation (Android.Content.Context context, System.String url) <0x77a7bd13d0 + 0x00747> in <3887a0d7d292416b83829cf88b593985>:0
  at Xamarin.Auth.CustomTabsConfiguration.Initialize (Android.App.Activity a) <0x77a7be0d24 + 0x00087> in <3887a0d7d292416b83829cf88b593985>:0
  at Xamarin.Auth.WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState) <0x77a7bdfe00 + 0x00247> in <3887a0d7d292416b83829cf88b593985>:0
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) <0x77aa8f42f0 + 0x00083> in <687f300d07ca4dd4ba94071c9d6e2850>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.8(intptr,intptr,intptr)

**Comment by kyluke** [comment]
Any fix for this yet? It's ridiculous that we need to wait this long.
