### ISSUE TITLE
UWP Exception on Auth_Error

### ISSUE THREAD

**Issue by bmarchionni** [xamarin/Xamarin.Auth#400]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [X] nuget version = 1.7.0

### Steps to reproduce

1. Authenticate using a WebAuthenticator page that has a cancel button.
2. When the user clicks the Cancel button Authenticator.Error fires and triggers an unhandleable exception from Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.Events.xaml.cs line 101

Platform:

-	[x] .NET version = UWP

### Expected behaviour

The Authenticator.Error should be raised but no exception should be throw. 

### Actual behaviour
An exception is thrown that can't be caught

I believe we just need to change Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.Events.xaml.cs line 101 from

private void auth_Error(object sender, AuthenticatorErrorEventArgs e)
{
    throw new Xamarin.Auth.AuthException("Auth Error");
}

to

private void auth_Error(object sender, AuthenticatorErrorEventArgs e)
{
    System.Diagnostics.Debug.WriteLine("Auth Error" + e.Message);
}

**Comment by luka454** [comment]
I can confirm this behavior. On each error, including canceling authentication (navigating back), the uncatchable exception is thrown and cause the application to crash.

This behavior is different from Android and iOS, where exception is not thrown and you can handle errors on your own.

### Workaround

1. Copy [WebAuthetnicatorPage](https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.Events.xaml.cs) (with [.cs](https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.xaml.cs) and [xaml](https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.xaml)) to your UWP project and remove throwing the exception
2. Copy [OAuthLoginPresenter](https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.UniversalWindowsPlatform/Presenters/OAuthPlatformPresenter.UniversalWindowsPlatform.cs) to you UWP project and change `pageType` to your WebAuthenticatorPage: `System.Type pageType = typeof(WebAuthenticatorPage);` (line [23](https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.UniversalWindowsPlatform/Presenters/OAuthPlatformPresenter.UniversalWindowsPlatform.cs#L23)).
3. Setup you OAuthLoginPresenter to be used. To do that remove default initialization `AuthenticationConfiguration.Init()` from UWP project and register your OAuthLoginPresenter with following code:

```
Xamarin.Auth.Presenters.OAuthLoginPresenter.PlatformLogin = (authenticator) =>
{
     var presenter = new OAuthLoginPresenter(); // Your OAuthLoginPresenter
     presenter.Login(authenticator);
};
```

**Comment by MGohil** [comment]
@luka454 

I am getting the following exception on successful Authentication credentials entered into web page.

> Xamarin.Auth.AuthException: Auth Error
>    at Xamarin.Auth.WebAuthenticatorPage.auth_Error(Object sender, AuthenticatorErrorEventArgs e)
>    at Xamarin.Auth.Authenticator.<>c__DisplayClass30_0.<OnError>b__0()
>    at Plugin.Threading.UIThreadRunInvoker.<>c__DisplayClass0_0.<BeginInvokeOnUIThread>b__0()

Tried the above Workaround, but no debug point hit on added classes.

NOTE : 

1. I didn't find `AuthenticationConfiguration.Init()` in my code. 
2. I added following code inside my UWP project's `OnLaunched `method.

```
Xamarin.Auth.Presenters.OAuthLoginPresenter.PlatformLogin = (authenticator) =>
{
    var presenter = new UWPOAuthLoginPresenter(); // Your OAuthLoginPresenter
    presenter.Login(authenticator);
};
```
3. The authentication was working few days ago. This error suddenly started poping in. 
4. However, Android and iOS is working fine.

Thanks.

**Comment by ValonK** [comment]
We currently have the same issue :( is there any workaround ?
